// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sis_Empleados.Models;

#nullable disable

namespace Sis_Empleados.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110032350_SincronizacionInicial")]
    partial class SincronizacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sis_Empleados.Models.Cargo_Empleado", b =>
                {
                    b.Property<int>("Id_CargoEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CargoEmpleado"));

                    b.Property<string>("Cargo_De_Empleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Departamento")
                        .HasColumnType("int");

                    b.HasKey("Id_CargoEmpleado");

                    b.HasIndex("Id_Departamento");

                    b.ToTable("Cargo_Empleado");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Deduccion", b =>
                {
                    b.Property<int>("Id_TotalDeducciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_TotalDeducciones"));

                    b.Property<int>("Id_DetalleDeduccion")
                        .HasColumnType("int");

                    b.Property<int>("Id_EmpleadoSalario")
                        .HasColumnType("int");

                    b.Property<int>("Monto_Deduccion")
                        .HasColumnType("int");

                    b.HasKey("Id_TotalDeducciones");

                    b.HasIndex("Id_DetalleDeduccion");

                    b.HasIndex("Id_EmpleadoSalario");

                    b.ToTable("Deduccion");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Departamento", b =>
                {
                    b.Property<int>("Id_Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Departamento"));

                    b.Property<string>("Departamento_De_Trabajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Departamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Detalle_Deduccion", b =>
                {
                    b.Property<int>("Id_DetalleDeduccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DetalleDeduccion"));

                    b.Property<decimal>("Deduccion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_TipoDeducciones")
                        .HasColumnType("int");

                    b.HasKey("Id_DetalleDeduccion");

                    b.HasIndex("Id_TipoDeducciones");

                    b.ToTable("Detalle_Deduccion");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Empleado", b =>
                {
                    b.Property<int>("Id_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Empleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_CargoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Empleado");

                    b.HasIndex("Id_CargoEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Empleado_Salario", b =>
                {
                    b.Property<int>("Id_EmpleadoSalario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_EmpleadoSalario"));

                    b.Property<int>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Periodo")
                        .HasColumnType("int");

                    b.Property<int>("Salario_Base")
                        .HasColumnType("int");

                    b.HasKey("Id_EmpleadoSalario");

                    b.HasIndex("Id_Empleado");

                    b.HasIndex("Id_Periodo");

                    b.ToTable("Empleado_Salario");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Periodo", b =>
                {
                    b.Property<int>("Id_Periodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Periodo"));

                    b.Property<string>("Periodo_De_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Periodo");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Permiso", b =>
                {
                    b.Property<int>("Id_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Permiso"));

                    b.Property<string>("Nombre_Permiso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Permiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Rol_Permiso", b =>
                {
                    b.Property<int>("Id_RolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_RolPermiso"));

                    b.Property<int>("Id_Permiso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.HasKey("Id_RolPermiso");

                    b.HasIndex("Id_Permiso");

                    b.HasIndex("Id_Rol");

                    b.ToTable("Rol_Permiso");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Tipo_Deducciones", b =>
                {
                    b.Property<int>("Id_TipoDeducciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_TipoDeducciones"));

                    b.Property<string>("Nombre_Deduccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_TipoDeducciones");

                    b.ToTable("Tipo_Deducciones");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Turno", b =>
                {
                    b.Property<int>("Id_Turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Turno"));

                    b.Property<string>("Tipo_Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Turno");

                    b.ToTable("Turno");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Turno_Empleado", b =>
                {
                    b.Property<int>("Id_TurnoEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_TurnoEmpleado"));

                    b.Property<int>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Turno")
                        .HasColumnType("int");

                    b.HasKey("Id_TurnoEmpleado");

                    b.HasIndex("Id_Empleado");

                    b.HasIndex("Id_Turno");

                    b.ToTable("Turno_Empleado");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<byte[]>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Empleado");

                    b.HasIndex("Id_Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Cargo_Empleado", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Departamento", "Departamento")
                        .WithMany("Cargos")
                        .HasForeignKey("Id_Departamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Deduccion", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Detalle_Deduccion", "DetalleDeduccion")
                        .WithMany("Deducciones")
                        .HasForeignKey("Id_DetalleDeduccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sis_Empleados.Models.Empleado_Salario", "EmpleadoSalario")
                        .WithMany("Deducciones")
                        .HasForeignKey("Id_EmpleadoSalario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetalleDeduccion");

                    b.Navigation("EmpleadoSalario");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Detalle_Deduccion", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Tipo_Deducciones", "TipoDeduccion")
                        .WithMany("DetallesDeduccion")
                        .HasForeignKey("Id_TipoDeducciones")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDeduccion");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Empleado", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Cargo_Empleado", "CargoEmpleado")
                        .WithMany("Empleados")
                        .HasForeignKey("Id_CargoEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoEmpleado");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Empleado_Salario", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Empleado", "Empleado")
                        .WithMany("Salarios")
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sis_Empleados.Models.Periodo", "Periodo")
                        .WithMany("EmpleadoSalarios")
                        .HasForeignKey("Id_Periodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Rol_Permiso", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("Id_Permiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sis_Empleados.Models.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Turno_Empleado", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Empleado", "Empleado")
                        .WithMany("Turnos")
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sis_Empleados.Models.Turno", "Turno")
                        .WithMany("TurnosEmpleados")
                        .HasForeignKey("Id_Turno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Usuario", b =>
                {
                    b.HasOne("Sis_Empleados.Models.Empleado", "Empleado")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sis_Empleados.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Cargo_Empleado", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Departamento", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Detalle_Deduccion", b =>
                {
                    b.Navigation("Deducciones");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Empleado", b =>
                {
                    b.Navigation("Salarios");

                    b.Navigation("Turnos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Empleado_Salario", b =>
                {
                    b.Navigation("Deducciones");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Periodo", b =>
                {
                    b.Navigation("EmpleadoSalarios");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Tipo_Deducciones", b =>
                {
                    b.Navigation("DetallesDeduccion");
                });

            modelBuilder.Entity("Sis_Empleados.Models.Turno", b =>
                {
                    b.Navigation("TurnosEmpleados");
                });
#pragma warning restore 612, 618
        }
    }
}
